global:
  resolve_timeout: 5m
  smtp_require_tls: false
  smtp_from: 'alertmanager@example.org'
  smtp_smarthost: 'localhost:25'
  #smtp_auth_username: 'alertmanager'
  #smtp_auth_password: 'password'
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'jun.d.ding@oracle.com'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
